// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

struct IndirectArgs 
{
    uint numVerticesPerInstance;
    uint numInstances;
    uint startVertexIndex;
    uint startInstanceIndex;
};

RWStructuredBuffer<IndirectArgs> _indirectArgsBuffer;

// Multiply the number of vertices by three to convert from triangles
[numthreads(1,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    _indirectArgsBuffer[0].numVerticesPerInstance *= 3;
}
